services:
  nginx:
    image: nginx:1.29.1
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    logging:
      driver: "none"
    networks:
      - public
      - private
  terminal-app:
    container_name: terminal-app
    build:
      context: ./terminal-app
      dockerfile: Dockerfile.dev
    env_file:
      - ./terminal-app/.env.dev
    volumes:
      - ./terminal-app/:/app
      - ./terminal-app/scripts/eliel.sh:/usr/bin/eliel
      - ./quest-files/bitcoin-password.txt:/home/web-user/bitcoin-password.txt
      - ./quest-files/hint-1:/home/web-user/hint-1
      - ./quest-files/hint-2:/hint-2
      - ./quest-files/hint-3.gpg:/tmp/.hint-3.gpg
      - ./quest-files/hint-2.5:/tmp/.hint-2.5
      - ./quest-files/gpg-passphrase:/var/log/gpg-passphrase
      - ./quest-files/easter-egg:/usr/bin/easter-egg
    networks:
      - private 
    security_opt:
      - apparmor:terminal-app
      - no-new-privileges:true
    read_only: true
    tmpfs:
     - /home/web-user/.gnupg:rw,uid=1001,gid=1001,mode=700,nosuid,nodev,noexec
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID

networks:
  public: {}
  private:
    internal: true