services:
  nginx:
    image: nginx:1.29.1
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    logging:
      driver: "none"
  terminal-app:
    container_name: terminal-app
    build:
      context: ./terminal-app
      dockerfile: Dockerfile.dev
    volumes:
      - ./terminal-app:/app
      - ./media:/app/media
      - ./scripts:/app/scripts
      - ./scripts/eliel:/usr/bin/eliel
    env_file:
      - ./terminal-app/.env.dev
    ports:
      - "8080:8080"          
    security_opt:
      - seccomp=./seccomp/seccomp.json
      - apparmor:terminal-app-compiled
      - no-new-privileges:true
    read_only: true
    cap_drop:
      - ALL
    # TODO: Add depends on nginx health for prod file
