services:
  nginx:
    image: nginx:1.29.1
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    logging:
      driver: "none"
  terminal-app:
    container_name: terminal-app
    build:
      context: ./terminal-app
      dockerfile: Dockerfile.dev
    env_file:
      - ./terminal-app/.env.dev
    volumes:
      - ./terminal-app/:/app
      - ./terminal-app/scripts/eliel.sh:/usr/bin/eliel
    security_opt:
      - seccomp=./seccomp/seccomp.json
      - apparmor:terminal-app
      - no-new-privileges:true
    read_only: true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
