FROM golang:1.23-bookworm

RUN apt-get update && \
    apt-get install -y sudo apparmor apparmor-utils apparmor-profiles

RUN useradd -m web-user

RUN mkdir -p /var/www && chown www-data:www-data /var/www

RUN echo "www-data ALL=(web-user) NOPASSWD: /bin/rbash" >> /etc/sudoers

USER www-data

WORKDIR /app

RUN go install github.com/air-verse/air@v1.61.7

COPY --chown=www-data:www-data go.mod go.sum ./

RUN go mod download

CMD ["air"]
