FROM golang:1.23-bookworm

RUN apt-get update && \
    apt-get install -y sudo apparmor apparmor-utils apparmor-profiles

RUN useradd -m -u 10000 -s /bin/rbash web-user

RUN mkdir -p /var/www && chown web-user:web-user /var/www

USER web-user

WORKDIR /app

RUN go install github.com/air-verse/air@v1.61.7

COPY --chown=web-user:web-user go.mod go.sum ./

RUN go mod download

CMD ["air"]
