FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    HF_HUB_DISABLE_TELEMETRY=1

WORKDIR /rag-chain

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

RUN useradd -m -u 1001 app-rag-chain

RUN mkdir -p /rag-chain/store && chown -R app-rag-chain:app-rag-chain /rag-chain

USER app-rag-chain

EXPOSE 5000

CMD ["python", "main.py"]
