FROM debian:bookworm

RUN apt update \
  # mpv = video/audio player
  # libcaca0 = ASCII art video output
  # libasound2 = ALSA audio support
  # ncurses-term = terminal definitions (xterm-256color etc.)
  # TODO: Remove curl and ping for prod
  && apt install -y mpv  --no-install-recommends \
    libcaca0 libasound2 ncurses-term curl iputils-ping \
  && rm -rf /var/lib/apt/lists/*

# Set terminal type so apps (mpv/caca) know how to render
ENV TERM=xterm-256color

RUN useradd -m -u 1001 -s /bin/rbash web-user

RUN mkdir -p /var/www && chown web-user:web-user /var/www

RUN echo 'PS1="\[\e[1;32m\]user\[\e[0m\]@\[\e[1;32m\]server\[\e[0m\]:\[\e[1;34m\]\w\[\e[0m\] \$ "' >> /home/web-user/.bashrc

USER web-user

WORKDIR /app

EXPOSE 8080

CMD ["./terminal-app"]
