FROM debian:bookworm

# RUN apt update && apt install -y bash && rm -rf /var/lib/apt/lists/*

RUN useradd -m -u 1001 -s /bin/rbash web-user

RUN mkdir -p /var/www && chown web-user:web-user /var/www

USER web-user

WORKDIR /app

EXPOSE 8080

CMD ["./terminal-app"]
