FROM debian:bookworm

WORKDIR /app

RUN apt update \
  # mpv = video/audio player
  # libcaca0 = ASCII art video output
  # ncurses-term = terminal definitions (xterm-256color etc.)
  # TODO: Remove curl and ping for prod
  && apt install -y mpv  --no-install-recommends \
    libcaca0 ncurses-term curl iputils-ping \
  && rm -rf /var/lib/apt/lists/*

# Set terminal type so apps (mpv/caca) know how to render
ENV TERM=xterm-256color

RUN useradd -m -u 1001 -s /bin/rbash web-user

COPY bashrc-append /app

RUN cat ./bashrc-append >> /home/web-user/.bashrc

USER web-user

EXPOSE 8080

CMD ["./terminal-app"]
